### ISSUE TITLE
`.Variants.List` API is changed

### ISSUE THREAD

**Issue by Jannchie** [NdoleStudio/lemonsqueezy-go#20] opened 2024-01-25 04:37 UTC
Thank you for making such a library.

I found that some of the interfaces have changed, for example the API for List Variants no longer parses the returned content correctly.
https://docs.lemonsqueezy.com/api/variants

Also, lemonsqueezy has added Price as an object to retrieve, which is not yet supported by the library.
https://docs.lemonsqueezy.com/api/prices#the-price-object

**Comment by AchoArnold** [comment] 2024-01-25 20:23
Hello @Jannchie 
I've implemented the new Price API endpoints, I didn't see what was wrong with the `variants` API appart from the introduction of the `TestMode: boolean` field. Also did you notice any other changes to the API's?

**Comment by Jannchie** [comment] 2024-01-26 04:38
Thanks for the quick reply.


I get an error when parsing with this API:

```
variants, _, err := s.client.Variants.List(ctx)
```

error message is: 

```
"json: cannot unmarshal string into Go struct field VariantAttributes.data.attributes.price of type int"
```

Can't you reproduce the problem on your end?

**Comment by AchoArnold** [comment] 2024-01-26 05:06
Hello @Jannchie 

I cannot reproduce the issue. Which version of this `lemonsqueezy-go` client are you using?

I checked the api response and the `data.attriubtes.price` is `int` instead of `string` https://docs.lemonsqueezy.com/api/variants

**Comment by Jannchie** [comment] 2024-01-26 05:42
I'm using v1.1.0...

**Comment by AchoArnold** [comment] 2024-01-26 06:02
@Jannchie 
I just saw the problem with a new price, I'll contact the LemonSqueezy team to fix it. Some prices have `string` and others have `int` I think it's up to the API team to fix this inconsitency.

**Comment by AchoArnold** [comment] 2024-03-04 05:59
Fixed in https://github.com/NdoleStudio/lemonsqueezy-go/commit/8da1ed401d4607e14d60919d59c543682f809488

**Closed by AchoArnold** 2024-03-04 05:59 UTC
